<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>UK Tea &amp; Infusions Association - Frequently Asked Questions</title>
    <?php include_once('includes/static-resources.php'); ?>
</head>
<body class="faqs">

    <div class="page">

        <div class="header">

            <a href="#mobile-navigation" id="mobile-navigation-button" class="mobile-navigation-button"><i class="fa fa-bars"></i></a>

            <h1 class="logo">
                <span>
                    <span>
                        <a href="index.php">
                            <img src="images/logo.png" alt="" />
                        </a>
                    </span>
                </span>
            </h1>

            <ul class="aux-navigation">
                <li class="tw"><a href="https://twitter.com/ukteacouncil" title="Twitter" target="_blank">Twitter</a></li>
                <li><a href="index.php" title="Log-out">Log-out</a></li>
                <li class="first"><a href="/site-map" title="Sitemap">Sitemap</a></li>
                <li><a href="/terms-conditions" title="Terms &amp; Conditions">T&amp;Cs</a></li>
                <li class="last"><a href="/privacy-policy" title="Privacy Policy">Privacy Policy</a></li>
            </ul>

            <?php include_once('includes/search-box.php'); ?>

            <div class="navigation">
                <ul id="navigation-list" class="list">
                    <li class="first option-one has-dropdown"><a href="about.php">About UKTIA</a>
                        <ul>
                            <li class="first"><a href="benefits.php">Members Benefits</a></li>
                            <li class="last"><a href="index.php">Members Log-out</a></li>
                        </ul>
                    </li>
                    <li class="option-two has-dropdown"><a href="pulse.php">The Pulse</a>
                        <ul>
                            <li class="first"><a href="essential-reading.php">Essential Reading</a></li>
                            <li><a href="video-update.php">Video Update</a></li>
                            <li class="last"><a href="press.php">Tea in the Press</a></li>
                        </ul>
                    </li>
                    <li class="option-three has-dropdown active"><a href="members-reference.php">Membership Reference Info</a>
                        <ul>
                            <li class="first"><a href="fdf-access.php">Access to FDF Website</a></li>
                            <li><a href="annual-reports.php">Annual reports</a></li>
                            <li><a href="crisis-response.php">Crisis &amp; Response Procedures</a></li>
                            <li class="active"><a href="faqs.php">FAQs</a></li>
                            <li><a href="industry-partners.php">Industry Partners</a></li>
                            <li><a href="/key-contacts">Key Contact &amp; Profiles</a></li>
                            <li><a href="/members">Members Directory</a></li>
                            <li><a href="/rules-regulation">Member's Rules &amp; regulations</a></li>
                            <li class="last"><a href="/operating-groups">Operating Groups &amp; Mandates</a></li>
                        </ul>
                    </li>
                    <li class="last option-fours"><a href="/circulars">Circulars</a></li>
                </ul>
            </div>

            <div class="cboth"></div>
        </div><!-- .header -->

        <div class="body">

            <div class="section">
                <div class="wide left">
                    <div class="copy-padding">

                        <h2>Frequently Asked Questions</h2>
                        <p>The topics selected for inclusion here have been generated by UKTIA members, wider tea industry companies, and the general public and generally fall into the technical or scientific category. We aim to provide a definitive answer that is generally accepted by UKTIA member experts.</p>

                        <div class="entries">


                            <div class="entry">

                                <h3>Is decaffeinated tea completely caffeine free?</h3>
                                <dl>
                                    <dt>Answered by:</dt>
                                    <dd>Bill Gorman</dd>
                                    <dt>Publish date:</dt>
                                    <dd>03/04/2013</dd>
                                </dl>
                                <p>
                                    No, after the decaffeination process a fractional level of caffeine remains in the dry leaf. The European tea trade operates to a standard of 0.2g per 100g.</p>
                                <p>
                                    Three methods exist for extracting caffeine. Di Choloromethylene (solvent), Ethyl Acetate (organic solvent) and Super Critical Co2 (high temperature under pressure). All methods are governed by legal limits. &nbsp; &nbsp; &nbsp; &nbsp;</p>
                                <p>
                                    The European Union standard for solvent residues in tea is a maximum of 5ppm. Tests show that tea imported to the UK typically has detectable levels of between two and three ppm in the dry leaf. Furthermore, &quot;The brewing process renders solvent residues virtually undetectable&quot;.</p>


                            </div>


                            <div class="entry">

                                <h3>How much Caffeine is in Tea?</h3>
                                <dl>
                                    <dt>Answered by:</dt>
                                    <dd>Bill Gorman</dd>
                                    <dt>Publish date:</dt>
                                    <dd>03/04/2013</dd>
                                </dl>
                                <p>
                                    Caffeine is the world&#39;s most popular drug and can be found in many beverages including tea.&nbsp; It is a psychostimulant that is widely used to enhance alertness and improve performance. A recent American study was conducted to determine the concentration of caffeine in 20 assorted commercial tea products.&nbsp; The teas were brewed under a variety of conditions including different serving sizes and steep-times. Caffeine was isolated from the teas with liquid-liquid extraction and quantitated by gas chromatography with nitrogen-phosphorus detection. Caffeine concentrations in white, green, and black teas ranged from 14 to 61 mg per serving (6 or 8 oz) with no observable trend in caffeine concentration due to the variety of tea.&nbsp; The decaffeinated teas contained less than 12 mg of caffeine per serving, and caffeine was not detected in the herbal tea varieties. In most instances, the 6 and 8-oz serving sizes contained similar caffeine concentrations per ounce, but the steep-time affected the caffeine concentration of the tea. These findings indicate that most brewed teas contain less caffeine per serving than brewed coffee.</p>
                                <p>
                                    For comprehensive facts on caffeine please go to the Tea Advisory panel website using the following link - <a href="http://www.teaadvisorypanel.com/facts" title="Go to the Tea Adicory Panel website....">http://www.teaadvisorypanel.com/facts</a></p>


                            </div>


                            <div class="entry">

                                <h3>Why is the foil used in sealing tea bags not recyclable?</h3>
                                <dl>
                                    <dt>Answered by:</dt>
                                    <dd>Bill Gorman</dd>
                                    <dt>Publish date:</dt>
                                    <dd>03/04/2013</dd>
                                </dl>
                                <p>
                                    Foil wrapping has two functions; the first is hygiene, particularly in food-service or in hotels as part of the in-room tea making facility, the second is typically for tea products that have additional flavours, bergamot for Earl Grey tea for example. This ensures that the flavoured oils do not taint other tea products and the quality and freshness of the ingredient is maintained.</p>
                                <p>
                                    The tea industry is one of the most environmentally friendly industries, and over the years has changed operating, transportation and packaging procedures to significantly reduce its environmental impact and improve sustainability. Wooden pallets for example are rarely used in transportation and pesticide usage has been dramatically altered and reduced. It is true that some brands have not yet moved their foil wrap product to a recyclable material, the fundamental reason is cost. A fully recyclable foil material costs five times more than the existing product, and this significant cost increase has not been accepted by the major retailers and wholesalers. One further factor causing the delay in the evolution to fully recyclable foil is that technologically speaking, new recyclable foil products are not offering the same barrier protection as the existing materials.</p>
                                <p>
                                    Even though foil wrapped products account for a fraction of total daily tea consumed tonnage, the tea industry would willingly adopt a recyclable foil product if retailers would accept the cost increase, and a technically sound cost effective material was available.</p>


                            </div>


                            <div class="entry">

                                <h3>My customer wants to know what the moisture content of tea would be in the dried leaf</h3>
                                <dl>
                                    <dt>Answered by:</dt>
                                    <dd>Bill Gorman</dd>
                                    <dt>Publish date:</dt>
                                    <dd>03/04/2013</dd>
                                </dl>
                                <p>
                                    When tea emerges from the drier at the end of the production process it will typically have moisture content of around 2%. Tea has a significant capacity to absorb moisture and it is not unusual for tea to have a moisture content of around 8% when landed in the UK. Packed tea which has a moisture content of around 4% will demonstrate very high quality packing and transportation care</p>


                            </div>


                            <div class="entry">

                                <h3>Is the average tea bag bio-degradable?</h3>
                                <dl>
                                    <dt>Answered by:</dt>
                                    <dd>Bill Gorman</dd>
                                    <dt>Publish date:</dt>
                                    <dd>03/04/2013</dd>
                                </dl>
                                <p>
                                    All major European environmental and recycling agencies agree that the tea bag is fully bio degradable, completely suitable for composting or as part of food waste recycling. The bag is now produced from Abaca Hemp, an organic plant. There is a fractional amount of polypropylene used in sealing certain bags, without that, material bags would not seal. The industry is working to find a sealing agent that is organic and cost effective.&nbsp; Bags that do not use polypropylene will secure the bag with a staple.</p>


                            </div>




                        </div>

                    </div>
                </div>

                <div class="narrow right">

                    <?php include('includes/member-updates-logged-in.php'); ?>

                    <?php include('includes/tea-in-the-press.php'); ?>

                </div>
                <div class="cboth"></div>
            </div>
        </div><!-- .body -->


        <?php include_once('includes/footer.php'); ?>

    </div><!-- .page -->

    <div class="back-to-top"><a href="#"><i class="fa fa-chevron-up"></i></a></div>
    <div class="mobile-navigation">
        <nav id="mobile-navigation" class="mobile-navigation-list">
            <ul>
                <li>
                    <form id="search" class="search" method="post" action="/search-results">
                        <div class="row">
                            <label class="label" for="term">Search</label>
                            <input class="term" type="text" id="term" name="term" value="">
                            <input class="button" type="submit" value="submit">
                        </div>
                    </form>
                </li>
                <li><a href="index.php">Home</a></li>
                <li><a href="about.php">About UKTIA</a>
                    <ul>
                        <li><a href="benefits.php">Members Benefits</a></li>
                        <li><a href="index.php">Members Log-out</a></li>
                    </ul>
                </li>
                <li><a href="pulse.php">The Pulse</a>
                    <ul>
                        <li><a href="essential-reading.php">Essential Reading</a></li>
                        <li><a href="video-update.php">Video Update</a></li>
                        <li><a href="press.php">Tea in the Press</a></li>
                    </ul>
                </li>
                <li><a href="members-reference.php">Membership Reference Info</a>
                    <ul>
                        <li><a href="fdf-access.php">Access to FDF Website</a></li>
                        <li><a href="annual-reports.php">Annual reports</a></li>
                        <li><a href="crisis-response.php">Crisis &amp; Response Procedures</a></li>
                        <li><a href="faqs.php">FAQs</a></li>
                        <li><a href="industry-partners.php">Industry Partners</a></li>
                        <li><a href="/key-contacts">Key Contact &amp; Profiles</a></li>
                        <li><a href="/members">Members Directory</a></li>
                        <li><a href="/rules-regulation">Member's Rules &amp; regulations</a></li>
                        <li><a href="/operating-groups">Operating Groups &amp; Mandates</a></li>
                    </ul>
                </li>
                <li><a href="/circulars">Circulars</a></li>
                <li><a href="/contact">Contact</a></li>
            </ul>
        </nav>
    </div>

    <script src="js/vendors/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="js/vendors/jquery.mmenu/jquery.mmenu.min.all.js"></script>
    <script src="js/uktia.js" type="text/javascript"></script>

</body>
</html>